### PR TITLE
Vanity

### PR DESCRIPTION
**Pull request by just-an-dev**

### CODE REVIEW

**Comment by micycle8778** [comment]
This sounds a bit interesting. I better watch this repo.

**Comment by micycle8778** [comment]
If you don't mind me asking, what is this branch for?

**Comment by micycle8778** [comment]
Hello?

**Comment by peoplma** [comment]
@rainbowasteroids vanity addresses are custom addresses that could start with something like DRainbow.  Functionality to buy a vanity address from the bot and have that be your sodogetip registered address is being added in.

**Comment by micycle8778** [comment]
Oh, okay. I know what a vanity address is, I just wanted to know what the integration of vanity addresses was for.

**Comment by peoplma** [comment]
One way of monetization basically, to help pay for server and development
costs.

**Pull request merged**
